name = "pbr"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
# ğŸ‘‡ ì•„ë˜ ì¤„ì„ ì¶”ê°€í•´ì£¼ì„¸ìš”! (ê²½ê³  í•´ê²°ìš©)
main = ".open-next/worker.js" 

[build]
command = "npm run build"

[site]
bucket = ".open-next/assets"
