name = "pbr"
main = "src/index.ts"
compatibility_date = "2025-12-30"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "endpr-db"
database_id = "f786c61f-1b1a-4c5b-8b8e-73cbd8965af7"

[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "endpr-assets"